from django.db import models


class ClassifiedChoice(models.TextChoices):
    Electronics = 'Electronics'
    ComputersAndNetworking = 'Computers & networking'
    BusinessAndIndustrial = 'Business & industrial'
    HomeAppliances = 'Home appliances'
    SportsEquipment = 'Sports equipment'
    ClothingAndAccessories = 'Clothing & accessories'
    CamerasAndImaging = 'Cameras & imaging'
    JewelryAndWatches = 'Jewelry & watches'
    Pets = 'Pets'
    MusicalInstruments = 'Musical instruments'
    Gaming = 'Gaming'
    BabyItems = 'BabyItems'
    Toys = 'Toys'
    TicketsVouchers = 'Tickets vouchers'
    Collectibles = 'Collectibles'
    Books = 'Books'
    Music = 'Music'
    FreeStuff = 'Free stuff'
    LostOrFound = 'Lost/Found'
    DVDsAndMovies = 'DVDs & movies'
    FurnitureHomeGarden = 'Furniture, home & garden'
    MobilePhonesAndTablets = 'Mobile phones & tablets'


class MobileOrTabletChoice(models.TextChoices):
    ACER = 'Acer'
    ALCATEL = 'Alcatel'
    APPLE_IPHONE = 'Apple iPhone'
    AsusASUS = 'Asus'
    BLACKBERRY = 'Blackberry'
    CAT = 'CAT'
    CECT = 'CECT'
    GOOGLE = 'Google'
    HTC = 'HTC'
    HEWLETT_PACKARD = 'Hewlett Packard'
    HUAWEI = 'Huawei'
    LG = 'LG'
    LAVA = 'Lava'
    LENOVO = 'Lenovo'
    MEIZU = 'Meizu'
    MOTOROLA = 'Motorola'
    NOKIA = 'Nokia'
    ONEPLUS = 'OnePlus'
    OPPO = 'Oppo'
    PALM = 'Palm'
    REALME = 'Realme'
    gSAMSUNG = 'Samsung'
    SANYO = 'Sanyo'
    SIDEKICK = 'Sidekick'
    SONY_ERICSSON = 'Sony Ericsson'
    VERTU = 'Vertu'
    VIVO = 'Vivo'
    XIAOMI = 'Xiaomi'
    YOTA = 'Yota'
    IMATE = 'iMate'
    OTHER = 'Other'


class MobileTabletAccessoriesChoice(models.TextChoices):
    BATTERIES = 'Batteries'
    CABLES_AND_ADAPTERS = 'Cables & Adapters'
    CAR_KITS = 'Car Kits'
    CASES_AND_SLEEVES = 'Cases & Sleeves'
    CHARGERS = 'Chargers'
    GIMBALS_AND_SELFIE_STICKS = 'Gimbals & Selfie Sticks'
    HEADSETS = 'Headsets'
    OTHERS = 'Others'


