from django.db import models


class CategoryKeywordChoice(models.TextChoices):
    MOTORS = 'Motors'
    CAR = 'Car'
    MOTOR_CYCLE = 'MotorCycle'
    AUTO_ACCESSORIES_AND_PARTS = 'AutoAccessoriesAndParts'
    Heavy_Vehicles = 'HeavyVehicles'
    OTHER_MOTORS = 'OtherMotors'

    Property_For_Sale = 'PropertyForSale'
    Residential_For_Sale = 'ResidentialForSale'
    Commercial_For_Sale = 'CommercialForSale'
    Multiple_Units_For_Sale = 'MultipleUnitsForSale'
    Land_For_Sale = 'LandForSale'
    OTHER_PROPERTY_FOR_SALE = 'OtherPropertyForSale'

    Property_For_Rent = 'PropertyForRent'
    Residential_Units_For_Rent = 'ResidentialUnitsForRent'
    Commercial_For_Rent = 'CommercialForRent'
    Rooms_For_Rent = 'RoomsForRent'
    OTHER_PROPERTY_FOR_RENT = 'OtherPropertyForRent'

    Jobs = 'Jobs'
    Job_Hiring = 'JobHiring'
    Job_Seeking = 'JobSeeking'

    Community = 'Community'
    Services = 'Services'
    CarLift = 'CarLift'
    Freelancers = 'Freelancers'
    Domestic = 'Domestic'
    Education = 'Education'
    Childcare = 'Childcare'
    Classes = 'Classes'
    Activities = 'Activities'
    Photography = 'Photography'
    Sports = 'Sports'
    Musical = 'Musical'
    Artists = 'Artists'
    Others = 'Others'

    Classified = 'Classified'
    Electronics = 'Electronics'
    Computers_And_Networking = 'ComputersAndNetworking'
    Computers = 'Computers'
    Computer_Components = 'ComputerComponents'
    Networking_And_Communication = 'NetworkingAndCommunication'
    Software = 'Software'
    Monitors_Printers_An_dOther_Peripherals = 'MonitorsPrintersAndOtherPeripherals'
    Other_Accessories = 'OtherAccessories'
    Business_And_Industrial = 'BusinessAndIndustrial'
    Home_Appliances = 'HomeAppliances'
    Sports_Equipment = 'SportsEquipment'
    Clothing_And_Accessories = 'ClothingAndAccessories'
    Cameras_And_Imaging = 'CamerasAndImaging'
    Jewelry_And_Watches = 'JewelryAndWatches'
    Musical_Instruments = 'MusicalInstruments'
    Gaming = 'Gaming'
    Baby_Items = 'BabyItems'
    Toys = 'Toys'
    Tickets_Vouchers = 'TicketsVouchers'
    Books = 'Books'
    Music = 'Music'
    Free_Stuff = 'FreeStuff'
    DVDs_And_Movies = 'DVDsAndMovies'
    Furniture_Home_Garden = 'FurnitureHomeGarden'
    Mobile_Phones_And_Tablets = 'MobilePhoneAndTablet'
    Mobile_Phones = 'MobilePhone'
    Mobile_Phone_Accessories = 'MobilePhoneAccessories'
    Tablets = 'Tablets'
    Other_Mobile_Phones_And_Tablets = 'OtherMobilePhoneAndTablet'
    Pets = 'Pets'
    Collectibles = 'Collectibles'
    Lost_Or_Found = 'LostOrFound'
    OTHER_CLASSIFIED = 'OtherClassified'

