# Generated by Django 3.2.4 on 2021-07-03 08:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('advertise', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='company_user', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='ComputerComponents',
            fields=[
                ('computersandnetworking_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='advertise.computersandnetworking')),
            ],
            bases=('advertise.computersandnetworking',),
        ),
        migrations.CreateModel(
            name='Computers',
            fields=[
                ('computersandnetworking_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='advertise.computersandnetworking')),
                ('memory', models.CharField(max_length=32)),
                ('processor_speed', models.CharField(max_length=32)),
                ('hard_drive', models.CharField(max_length=32)),
            ],
            bases=('advertise.computersandnetworking',),
        ),
        migrations.CreateModel(
            name='MonitorsPrintersAndOtherPeripherals',
            fields=[
                ('computersandnetworking_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='advertise.computersandnetworking')),
            ],
            bases=('advertise.computersandnetworking',),
        ),
        migrations.CreateModel(
            name='NetworkingAndCommunication',
            fields=[
                ('computersandnetworking_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='advertise.computersandnetworking')),
            ],
            bases=('advertise.computersandnetworking',),
        ),
        migrations.CreateModel(
            name='OtherAccessories',
            fields=[
                ('computersandnetworking_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='advertise.computersandnetworking')),
            ],
            bases=('advertise.computersandnetworking',),
        ),
        migrations.CreateModel(
            name='Software',
            fields=[
                ('computersandnetworking_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='advertise.computersandnetworking')),
            ],
            bases=('advertise.computersandnetworking',),
        ),
    ]
