# Generated by Django 3.2.4 on 2021-07-03 10:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('advertise', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OtherClassified',
            fields=[
                ('classified_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='advertise.classified')),
            ],
            bases=('advertise.classified',),
        ),
        migrations.CreateModel(
            name='OtherMotors',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seller_type', models.CharField(blank=True, max_length=64, null=True)),
                ('usage', models.CharField(blank=True, max_length=64, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='OtherPropertyForRent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('broker_id', models.CharField(blank=True, max_length=32, null=True)),
                ('lister_company_name', models.CharField(blank=True, max_length=32, null=True)),
                ('permit_number', models.CharField(blank=True, max_length=32, null=True)),
                ('agent_name', models.CharField(blank=True, max_length=32, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='OtherPropertyForSale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size', models.CharField(blank=True, max_length=32, null=True)),
                ('total_closing_fee', models.DecimalField(decimal_places=2, max_digits=10)),
                ('seller_type', models.CharField(blank=True, max_length=32, null=True)),
                ('completion_status', models.BooleanField(default=False)),
                ('landlord_name', models.CharField(blank=True, max_length=32, null=True)),
                ('broker_id', models.CharField(blank=True, max_length=32, null=True)),
                ('lister_company_name', models.CharField(blank=True, max_length=32, null=True)),
                ('permit_number', models.CharField(blank=True, max_length=32, null=True)),
                ('agent_name', models.CharField(blank=True, max_length=32, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
