# Generated by Django 3.2.4 on 2021-07-03 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rnd', '0002_baseadvertise_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='keyword',
            field=models.CharField(choices=[('Motors', 'Motors'), ('Car', 'Car'), ('MotorCycle', 'Motor Cycle'), ('AutoAccessoriesAndParts', 'Auto Accessories And Parts'), ('HeavyVehicles', 'Heavy Vehicles'), ('OtherMotors', 'Other Motors'), ('PropertyForSale', 'Property For Sale'), ('ResidentialForSale', 'Residential For Sale'), ('CommercialForSale', 'Commercial For Sale'), ('MultipleUnitsForSale', 'Multiple Units For Sale'), ('LandForSale', 'Land For Sale'), ('OtherPropertyForSale', 'Other Property For Sale'), ('PropertyForRent', 'Property For Rent'), ('ResidentialUnitsForRent', 'Residential Units For Rent'), ('CommercialForRent', 'Commercial For Rent'), ('RoomsForRent', 'Rooms For Rent'), ('OtherPropertyForRent', 'Other Property For Rent'), ('Jobs', 'Jobs'), ('JobHiring', 'Job Hiring'), ('JobSeeking', 'Job Seeking'), ('Community', 'Community'), ('Services', 'Services'), ('CarLift', 'Carlift'), ('Freelancers', 'Freelancers'), ('Domestic', 'Domestic'), ('Education', 'Education'), ('Childcare', 'Childcare'), ('Classes', 'Classes'), ('Activities', 'Activities'), ('Photography', 'Photography'), ('Sports', 'Sports'), ('Musical', 'Musical'), ('Artists', 'Artists'), ('Others', 'Others'), ('Classified', 'Classified'), ('Electronics', 'Electronics'), ('ComputersAndNetworking', 'Computers And Networking'), ('Computers', 'Computers'), ('ComputerComponents', 'Computer Components'), ('NetworkingAndCommunication', 'Networking And Communication'), ('Software', 'Software'), ('MonitorsPrintersAndOtherPeripherals', 'Monitors Printers An Dother Peripherals'), ('OtherAccessories', 'Other Accessories'), ('BusinessAndIndustrial', 'Business And Industrial'), ('HomeAppliances', 'Home Appliances'), ('SportsEquipment', 'Sports Equipment'), ('ClothingAndAccessories', 'Clothing And Accessories'), ('CamerasAndImaging', 'Cameras And Imaging'), ('JewelryAndWatches', 'Jewelry And Watches'), ('MusicalInstruments', 'Musical Instruments'), ('Gaming', 'Gaming'), ('BabyItems', 'Baby Items'), ('Toys', 'Toys'), ('TicketsVouchers', 'Tickets Vouchers'), ('Books', 'Books'), ('Music', 'Music'), ('FreeStuff', 'Free Stuff'), ('DVDsAndMovies', 'Dvds And Movies'), ('FurnitureHomeGarden', 'Furniture Home Garden'), ('MobilePhoneAndTablet', 'Mobile Phones And Tablets'), ('MobilePhone', 'Mobile Phones'), ('MobilePhoneAccessories', 'Mobile Phone Accessories'), ('Tablets', 'Tablets'), ('OtherMobilePhoneAndTablet', 'Other Mobile Phones And Tablets'), ('Pets', 'Pets'), ('Collectibles', 'Collectibles'), ('LostOrFound', 'Lost Or Found'), ('OtherClassified', 'Other Classified')], default='None', max_length=64),
        ),
    ]
